#makefile header, hakits add

AS86	=as86 -0 -a
LD86	=ld86 -0

AS	=as --32
LD	=ld 
LDFLAGS  = -m elf_i386 -s -x
CC	=gcc
CFLAGS	=-O -fleading-underscore -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce #-Wall

CPP	=cpp -nostdinc
AR  =ar
STRIP = strip
OBJCOPY = objcopy
